
if test -f ~/.bash_profile.local
then
    . ~/.bash_profile.local
fi

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# Save a ton of history
HISTSIZE=200000
HISTFILE=~/.history
SAVEHIST=200000

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
