name: Test Ubuntu

on:
  push:
    paths:
      - '**.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: make install_apt
      - run: make install
      - run: make
